engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
  govet:
    enabled: true
ratings:
  paths:
  - "**.go"
exclude_paths:
- "vendor/"
